name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create log directory
        run: mkdir -p cypress/logs 

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests in parallel
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --parallel --browser chrome --headless # --reporter mochawesome

      - name: Upload Cypress Logs
        uses: actions/upload-artifact@v4
        with:
          name: cypress-logs
          path: cypress/logs/

#      - name: Upload Mochawesome JSON Reports
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: mochawesome-json
#          path: cypress/reports/*.json

#      - name: Upload Mochawesome HTML Reports
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: mochawesome-html
#          path: cypress/reports/*.html

#      - name: Upload Cypress Screenshots (if tests fail)
#        if: failure()
#        uses: actions/upload-artifact@v4
#        with:
#          name: cypress-screenshots
#          path: cypress/screenshots

#      - name: Upload Cypress Videos
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: cypress-videos
#          path: cypress/videos
